tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "tnk-studio/tools"
tap "wvanlint/twf"
tap "xwmx/taps"
brew "fff"
brew "kubernetes-cli"
brew "rust"
brew "tnk-studio/tools/lazykube"
brew "wvanlint/twf/twf", args: ["HEAD"]
brew "xwmx/taps/hosts"

